n_conv_layers: [3, 4, 5]
max_channel: [32, 64, 128]
pool: [None]
pool_size: [0]
kernel_size: [3, 5, 7]
stride: [2, 3, 4, 5]
pool_stride: [0]
use_batch_norm: [True]
n_hidden_layers: [1, 2, 3]
max_hidden_neurons: [2560, 1240, 520]
hidden_activation: ["relu"]
lr: [0.001] #[1e-3, 5e-4, 1e-4]
